services:
  - type: web
    name: bika-marketplace-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: bika-marketplace-app
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: bika-marketplace-api
          property: host
